name: Deploy on GitHub Pages

on:
    workflow_run:
        workflows:
            -   Commit test
        types:
            -   completed

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    build:
        if: >
            github.event.workflow_run.conclusion == 'success' &&
            github.event.workflow_run.head_branch == 'main'

        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: client

        steps:
            -   name: Checkout files
                uses: actions/checkout@v4
                with:
                    sparse-checkout: client
                    sparse-checkout-cone-mode: true

            -   name: Setup `pnpm`
                uses: pnpm/action-setup@v4
                with:
                    version: 10

            -   name: Setup `node.js`
                uses: actions/setup-node@v4
                with:
                    node-version: 22
                    cache: pnpm
                    cache-dependency-path: client

            -   name: Install dependencies
                run: pnpm install --frozen-lockfile

            -   name: Build project
                run: pnpm build

            -   name: Upload artifact to GitHub Pages
                uses: actions/upload-pages-artifact@v4
                with:
                    path: client/dist

    deploy:
        needs: build

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        runs-on: ubuntu-latest

        steps:
            -   name: Deploy to GitHub Pages
                id: deployment
                uses: actions/deploy-pages@v4
