name: Commit test

on:
    push:
        branches:
            - "**"

jobs:
    test:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: client

        steps:
            -   name: Checkout files
                uses: actions/checkout@v4
                with:
                    sparse-checkout: client
                    sparse-checkout-cone-mode: true

            -   name: Setup `pnpm`
                uses: pnpm/action-setup@v4
                with:
                    version: 10

            -   name: Setup `node.js`
                uses: actions/setup-node@v4
                with:
                    node-version: 22
                    cache: pnpm
                    cache-dependency-path: client

            -   name: Install dependencies
                run: pnpm lock

            -   name: Audit dependencies
                run: pnpm audit

            -   name: Run linter
                run: pnpm lint

            -   name: Run tests
                run: pnpm test
